In [1]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model 
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
data_price = pd.read_csv('price_availability.csv', sep=";")
data_price

listing_id         day                       created  available  \
0           9810829  2018-12-08  2018-09-27 06:14:10.000+0000       True   
1           9810829  2018-12-08  2018-09-26 19:34:02.000+0000       True   
2          20897010  2018-12-09  2018-09-27 10:38:57.000+0000       True   
3          20897010  2018-12-09  2018-09-27 06:10:27.000+0000       True   
4          20897010  2018-12-09  2018-09-26 19:30:25.000+0000       True   
...             ...         ...                           ...        ...   
4748691    23608395  2018-09-06  2018-09-27 06:05:42.000+0000      False   
4748692    23608395  2018-09-06  2018-09-26 19:31:32.000+0000      False   
4748693     1447132  2018-12-27  2018-09-27 10:46:16.000+0000      False   
4748694     1447132  2018-12-27  2018-09-27 06:07:36.000+0000      False   
4748695     1447132  2018-12-27  2018-09-26 19:37:40.000+0000      False   

        local_currency  local_price  min_nights  
0                  EUR          160           1  
1                  EUR          160           1  
2                  EUR          172           2  
3                  EUR          172           2  
4                  EUR          172           2  
...                ...          ...         ...  
4748691            EUR           24           1  
4748692            EUR           24           1  
4748693            EUR          125           3  
4748694            EUR          125           3  
4748695            EUR          125           3  

[4748696 rows x 7 columns]

In [3]:
data_listing = pd.read_csv('listings_final.csv', sep=";")
data_listing

Unnamed: 0  listing_id                                      name  \
0             0    28581061                           La maison Clery   
1             1      661961       studio PARIS PLACE EDITH PIAF 75020   
2             2     1261705  chambre privée à louer @ paris oberkampf   
3             3     1318834            Appartement au coeur du Marais   
4             4     1677091                       Lovely & Quiet flat   
..          ...         ...                                       ...   
995         995    28335197          Studio cosy Jardin du Luxembourg   
996         996    28583013    Charmant  30m2 - Faubourg Saint Martin   
997         997    28628316       Cosy flat in the marais - Best area   
998         998    28792796         Appartement 3 chambres madeleine.   
999         999    28682896                          Village Jourdain   

             type   city                    neighborhood   latitude  \
0    private_room  Paris               2e arrondissement  48.869292   
1     entire_home  Paris                             NaN  48.867284   
2    private_room  Paris                             NaN  48.867894   
3     entire_home  Paris                      République  48.870370   
4     entire_home  Paris    Buttes-Chaumont - Belleville  48.874149   
..            ...    ...                             ...        ...   
995   entire_home  Paris  Saint Germain des Prés - Odéon  48.848695   
996   entire_home  Paris                      République  48.871623   
997   entire_home  Paris               2e arrondissement  48.867434   
998   entire_home  Paris             Madeleine - Vendôme  48.870109   
999  private_room  Paris    Buttes-Chaumont - Belleville  48.875425   

     longitude  person_capacity  beds  bedrooms  bathrooms  is_rebookable  \
0     2.348335                1     1         1        2.0          False   
1     2.403255                2     1         1        1.0          False   
2     2.375897                1     1         1        1.0          False   
3     2.358510                3     2         2        1.0          False   
4     2.373700                2     1         1        1.0          False   
..         ...              ...   ...       ...        ...            ...   
995   2.325857                2     1         0        1.0          False   
996   2.358006                3     1         1        1.0          False   
997   2.351771                4     2         1        1.0          False   
998   2.321475                6     4         2        1.5          False   
999   2.395240                2     1         1        1.0          False   

     is_new_listing  is_fully_refundable  is_host_highly_rated  \
0              True                 True                 False   
1             False                 True                  True   
2             False                 True                  True   
3             False                 True                 False   
4             False                 True                  True   
..              ...                  ...                   ...   
995            True                 True                 False   
996            True                 True                 False   
997            True                 True                  True   
998            True                 True                 False   
999            True                 True                 False   

     is_business_travel_ready  pricing_weekly_factor  pricing_monthly_factor  
0                       False                   1.00                    1.00  
1                       False                   0.88                    0.69  
2                       False                   1.00                    1.00  
3                       False                   0.82                    0.48  
4                       False                   0.95                    0.90  
..                        ...                    ...                     ...  
995 

In [10]:
data_price = data_price.groupby("listing_id").mean()
data_price

available  local_price  min_nights
listing_id                                    
5396         0.011494   102.363985    2.000000
7397         0.168297   110.107632   11.000000
9342         0.309198   396.863014    2.784736
10010        0.254593   136.154856    4.955381
10270        0.511688   105.779221    4.937662
...               ...          ...         ...
28836096     0.082707   321.428571    1.022556
28838519     0.083333    54.483333    5.000000
28840013     0.743083   112.122530    2.000000
28846494     0.225564   168.037594    4.000000
28851976     0.812030   128.000000    2.000000

[11749 rows x 3 columns]

In [5]:
df = pd.merge(data_price,data_listing,on=['listing_id'])
df

listing_id  available  local_price  min_nights  Unnamed: 0  \
0         56093   0.000000   170.000000    4.000000          12   
1         57207   0.482940    49.952756    2.000000          13   
2        114543   0.140260   107.374026    3.716883          19   
3        149534   0.554974   169.000000    3.000000           9   
4        164255   0.100580    75.876209    3.841393          28   
..          ...        ...          ...         ...         ...   
994    28684174   0.785156   725.175781    1.046875         662   
995    28709644   0.954286   475.000000    6.000000         745   
996    28751412   0.521053   117.000000    1.000000          88   
997    28774896   0.840506   156.397468    1.000000         159   
998    28792796   0.639098    49.184211    5.000000         998   

                                                  name          type   city  \
0                          Beau duplex dans le Marais    entire_home  Paris   
1                             Belle Chambre pour court  private_room  Paris   
2                    Charming 1bdr 55m² - Eiffel Tower   entire_home  Paris   
3                   GREAT WARM FULL APT LE HAUT MARAIS   entire_home  Paris   
4                   Perfect place in Le Marais - Paris   entire_home  Paris   
..                                                 ...           ...    ...   
994  Chambre familiale vue jardin avec petit-déjeun...  private_room  Paris   
995                 LORD BYRON-SPACE& STYLE IN 8TH EME   entire_home  Paris   
996                         Malesherbes Monceau Monsen   entire_home  Paris   
997      5 min to invalides and 10 min to eiffel tower   entire_home  Paris   
998                  Appartement 3 chambres madeleine.   entire_home  Paris   

                    neighborhood   latitude  ...  beds  bedrooms  bathrooms  \
0              3e arrondissement  48.867284  ...     2         1        1.0   
1                      Vaugirard  48.846184  ...     1         1        1.0   
2                            NaN  48.849530  ...     1         1        1.0   
3                            NaN  48.866360  ...     2         1        1.0   
4              3e arrondissement  48.861398  ...     2         1        1.0   
..                           ...        ...  ...   ...       ...        ...   
994                       Ternes  48.879223  ...     0         1        1.0   
995               Champs-Elysées  48.872202  ...     2         1        1.0   
996                      Monceau  48.880923  ...     1         0        1.0   
997  Invalides - Ecole Militaire  48.852915  ...     1         1        1.0   
998          Madeleine - Vendôme  48.870109  ...     4         2        1.5   

     is_rebookable  is_new_listing  is_fully_refundable  is_host_highly_rated  \
0            False           False                 True                  True   
1            False           False                 True                 False   
2            False           False                 True                  True   
3            False           False                 True                  True   
4            False           False                 True                 False   
..             ...             ...                  ...                   ...   
994          False            True                 True                 False   
995          False            True                 True                 False   
996          False            True                 True                 False   
997          False            True                 True                 False   
998          False            True                 True                 False   

     is_business_travel_ready  pricing_weekly_factor  pricing_monthly_factor  
0                       False                   0.88                     1.0  
1                       False                   0.87                     1.0  
2                       False                   0.90                     0.9  
3            

In [6]:
x = np.array([df.person_capacity,df.bedrooms, df.bathrooms])
y = np.array(df.local_price)


In [7]:
y

array([ 170.        ,   49.95275591,  107.37402597,  169.        ,
         75.8762089 ,  284.35356201,   36.58961039,  300.        ,
        101.37984496,   67.20833333,   60.74093264,   38.        ,
         92.        ,   66.21204188,   79.68041237,   90.09819121,
        170.        ,  115.7544757 ,  283.76115486,  144.74424552,
        347.67015707,  115.        ,  105.        ,  154.65384615,
        380.        ,   44.16569201,  233.69170984,  146.        ,
        147.96623377,  105.        ,  163.47286822,  190.        ,
        180.95287958,  128.8630491 ,   44.47368421,  163.28571429,
         94.        ,   94.97619048,  218.96373057,  234.89460154,
        300.78640777,   62.        ,   59.02349869,   80.24479167,
         53.        ,   92.        ,  210.87855297,  278.90625   ,
        165.        ,  179.67315175,  105.71849866,   43.84615385,
        105.15873016,  165.        ,  172.67822736,  109.        ,
         42.86340206,  220.        ,  136.57559682,  240.     

In [8]:
x

array([[4. , 2. , 2. , ..., 2. , 2. , 6. ],
       [1. , 1. , 1. , ..., 0. , 1. , 2. ],
       [1. , 1. , 1. , ..., 1. , 1. , 1.5]])

In [9]:
x.shape

(3, 999)

In [13]:
from sklearn.model_selection import train_test_split
x=x.reshape((999,3))
x_test, x_train, y_test, y_train = train_test_split(x, y, test_size=0.30, random_state=42)

In [23]:
y_train.shape

(699,)

In [40]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
reg.coef_

array([ 0.05105275, -2.10531958, -4.05737923])

In [42]:
reg.intercept_

197.2822629665012

In [43]:
print("Coefficients beta_j :\n{}\nCoefficients INTERCEPT beta0 :\n{}".format(reg.coef_,reg.intercept_))

Coefficients beta_j :
[ 0.05105275 -2.10531958 -4.05737923]
Coefficients INTERCEPT beta0 :
197.2822629665012


In [49]:
yPredict = reg.predict(x_test)


In [53]:
print("taille du vecteur Y_pred : {} ".format(len(yPredict)))

taille du vecteur Y_pred : 300 


In [55]:
print("Mean squared error: {0}\nR2 : {1}".format(mean_squared_error(y_test,yPredict),r2_score(y_test,yPredict)))

Mean squared error: 35046.99302862562
R2 : -0.010380011409886869


In [56]:
r2_score(y_test, yPredict)

-0.010380011409886869